# If set to true, the "all" commands will affect the issuer
# of the command as well as everyone else online. If not,
# the issuer will not be affected.
affect-command-issuer: true

commands:
  huball: true
  kickall: true
  tpall: true
  setspawn: true
  ip: true
  hideplayers: true
  showplayers: true
  killall: true
  day: true
  night: true
  clearall: true
  giveall: true
  
messages:
  huball-message: '&7&lServer&5>> &b&lYou have been telported to the lobby!'
  default-kickall-message: '&7&lServer&5>> &b&lYou have been kicked!'
  tpall-message: '&7&lServer&5>> &b&lYou have been teleported!'
  killall-message: '&7&lServer&5>> &b&lYou were killed!'
  clearall-message: '&7&lServer&5>> &b&lYour inventory has been cleared!'
  giveall-message: '&7&lServer&5>> &b&lYou received an item!'
  command-disabled-message: '&7&lServer&5>> This command is disabled.'

update-checker: true
  
  
