affect-command-issuer:
  huball: true
  kickall: false
  tpall: true
  killall: false
  clearall: true
  giveall: true

commands:
  huball: true
  kickall: true
  tpall: true
  setspawn: true
  ip: true
  hideplayers: true
  showplayers: true
  killall: true
  day: true
  night: true
  clearall: true
  giveall: true
  
messages:
  huball: '&7&lServer&5>> &b&lYou have been teleported to the lobby!'
  default-kickall: '&7&lServer&5>> &b&lYou have been kicked!'
  tpall: '&7&lServer&5>> &b&lYou have been teleported!'
  killall: '&7&lServer&5>> &b&lYou were killed!'
  clearall: '&7&lServer&5>> &b&lYour inventory has been cleared!'
  giveall: '&7&lServer&5>> &b&lYou received an item!'

  clearall-complete: '&7&lServer&5>> &7Cleared inventory of all players.'
  day-complete: '&7&lServer&5>> &7Time set to day.'
  giveall-complete: '&7&lServer&5>> &7Given all players {amount} of {item}.'
  hideplayers-complete: '&7&lServer&5>> &7Hidden players from your view.'
  huball-complete: '&7&lServer&5>> &7All players teleported to the hub.'
  ip-complete: '&7&lServer&5>> &7The IP address of &b{player} &7is &b{ip}&7.'
  kickall-complete: '&7&lServer&5>> &7Kicked all players.'
  killall-complete: '&7&lServer&5>> &7Killed all players.'
  night-complete: '&7&lServer&5>> &7Time set to night.'
  setspawn-complete: '&7&lServer&5>> &7Spawn set to your position.'
  showplayers-complete: '&7&lServer&5>> &7You can now see players.'
  tpall-complete: '&7&lServer&5>> &7Teleported all players.'

  clearall-usage: '&CUsage: /clearall'
  day-usage: '&CUsage: /day'
  giveall-usage: '&CUsage: /giveall <item> [amount]'
  hideplayers-usage: '&CUsage: /hideplayers'
  huball-usage: '&CUsage: /huball'
  ip-usage: '&CUsage: /ip <player>'
  kickall-usage: '&CUsage: /kickall <reason>'
  killall-usage: '&CUsage: /killall'
  night-usage: '&CUsage: /day'
  setspawn-usage: '&CUsage: /setspawn'
  showplayers-usage: '&CUsage: /showplayers'
  tpall-usage: '&CUsage: /tpall <x> <y> <z> [world]'

  no-permission: '&4You do not have access to that command.'
  autohub-required: '&CError: AutoHub is not installed or the hub is not set.'
  must-be-a-player: '&CYou must be a player to execute this command.'
  command-disabled: '&7&lServer&5>> This command is disabled.'

  player-not-found: '&CPlayer {player} was not found.'
  world-not-found: '&CWorld {world} was not found.'
  item-type-not-found: '&CItem type {type} was not found.'

update-checker: true
  
  
