commands:
  huball: true
  kickall: true
  tpall: true
  setspawn: true
  ip: true
  hideplayers: true
  showplayers: true
  killall: true
  day: true
  night: true
  clearall: true
  giveall: true
  
messages:
  huball-message: 'You have been telported to the lobby!'
  default-kickall-message: 'You have been kicked from the server!'
  tpall-message: 'You have been teleported!'
  killall-message: 'You were killed!'
  clearall-message: 'Your inventory has been cleared!'
  giveall-message: 'You received an item!'
  command-disabled-message: 'This command is disabled.'
  


  
  
