name: ${project.name}
main: net.twilightdevelopment.plugin.extracommands.ExtraCommands
version: ${project.version}
author: gzx
softdepend: [AutoHub]
api-version: 1.13

commands:
  huball:
    description: Teleports all users online except those with the extracommands.dodgehuball permission to the hub location/server (requires AutoHub v1.1.0 or later)
    usage: /huball
    
  tpall:
    description: Teleports all online users except those with the extracommands.dodgetpall permission to specified location
    usage: /tpall <x> <y> <z> (optional)<world>
    
  kickall:
    description: Kicks all online players except those with the extracommands.dodgekickall permission from the server
    usage: /kickall <reason>
   
  setspawn:
    description: Sets the spawn location
    usage: /setspawn
   
  ip:
    description: Gets the IP of a player
    usage: /ip <player>
    
  hideplayers:
    description: Hides all players from sender
    usage: /hideplayers
  
  showplayers:
    description: Reveals all players from sender
    usage: /showplayers
    
  killall:
    description: Kills all online players except those with the extracommands.dodgekillall permission
    usage: /killall

  day:
    description: Sets the time to day
    usage: /day
    
  night:
    description: Sets the time to night
    usage: /night
    
  clearall:
    description: Clears the inventory of all players except those with the extracommands.dodgeclearall permission
    usage: /clearall
    
  giveall:
    description: Gives an item to all players
    usage: /giveall <item> [amount]

  extracommands:
    description: Base ExtraCommands command
    usage: /extracommands (info | reload)


permissions:
  extracommands.huball:
    default: false
  
  extracommands.dodgehuball:
    default: false
  
  extracommands.tpall:
    default: false
  
  extracommands.dodgetpall:
    default: false
  
  extracommands.kickall:
    default: false
  
  extracommands.dodgekickall:
    default: false
  
  extracommands.setspawn:
    default: false
    
  extracommands.ip:
    default: false
    
  extracommands.hideplayers:
    default: false
    
  extracommands.showplayers:
    default: false
    
  extracommands.killall:
    default: false
    
  extracommands.dodgekillall:
    default: false
    
  extracommands.day:
    default: false
    
  extracommands.night:
    default: false
    
  extracommands.clearall:
    default: false
    
  extracommands.dodgeclearall:
    default: false
    
  extracommands.giveall:
    default: false
  
  extracommands.dodgegiveall:
    default: false

  extracommands.info:
    default: true

  extracommands.reload:
    default: false
    
 
  
  
  
  
  